package com.dzmsoft.ucs.base.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dzmsoft.ucs.base.pojo.UcsPermission;
import com.dzmsoft.ucs.base.pojo.UcsPermissionExample;
import com.dzmsoft.ucs.base.pojo.udf.UcsUserPermissionExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface UcsPermissionMapper {
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int countByExample(UcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByExample(UcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insert(UcsPermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insertSelective(UcsPermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    List<UcsPermission> selectByExample(UcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    UcsPermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") UcsPermission record,
            @Param("example") UcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExample(@Param("record") UcsPermission record,
            @Param("example") UcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKeySelective(UcsPermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKey(UcsPermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    PageList<UcsPermission> selectByExample(UcsPermissionExample example, PageBounds pageBounds);

    /**
     * 根据用户获取权限
     * @param example
     * @return
     */
    List<UcsPermission> selectPermissionsByUser(UcsUserPermissionExample example);
}