package com.dzmsoft.ucs.base.dao;

import com.dzmsoft.ucs.base.pojo.UcsRole;
import com.dzmsoft.ucs.base.pojo.UcsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface UcsRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int countByExample(UcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByExample(UcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insert(UcsRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insertSelective(UcsRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    List<UcsRole> selectByExample(UcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    UcsRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") UcsRole record,
            @Param("example") UcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExample(@Param("record") UcsRole record, @Param("example") UcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKeySelective(UcsRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKey(UcsRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    PageList<UcsRole> selectByExample(UcsRoleExample example, PageBounds pageBounds);
}