package com.dzmsoft.ucs.base.dao;

import com.dzmsoft.ucs.base.pojo.UcsRolePermission;
import com.dzmsoft.ucs.base.pojo.UcsRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface UcsRolePermissionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int countByExample(UcsRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByExample(UcsRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insert(UcsRolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int insertSelective(UcsRolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    List<UcsRolePermission> selectByExample(UcsRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    UcsRolePermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") UcsRolePermission record,
            @Param("example") UcsRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByExample(@Param("record") UcsRolePermission record,
            @Param("example") UcsRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKeySelective(UcsRolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    int updateByPrimaryKey(UcsRolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_role_permission
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    PageList<UcsRolePermission> selectByExample(UcsRolePermissionExample example,
            PageBounds pageBounds);
}