package com.dzmsoft.ucs.base.dao;

import com.dzmsoft.ucs.base.pojo.UcsUser;
import com.dzmsoft.ucs.base.pojo.UcsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

public interface UcsUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int countByExample(UcsUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int deleteByExample(UcsUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int insert(UcsUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int insertSelective(UcsUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    List<UcsUser> selectByExample(UcsUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    UcsUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") UcsUser record,
            @Param("example") UcsUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int updateByExample(@Param("record") UcsUser record, @Param("example") UcsUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int updateByPrimaryKeySelective(UcsUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    int updateByPrimaryKey(UcsUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ucs_user
     * @mbggenerated  Mon Nov 14 14:46:54 CST 2016
     */
    PageList<UcsUser> selectByExample(UcsUserExample example, PageBounds pageBounds);
}