package com.dzmsoft.ucs.ccs.dao;

import com.dzmsoft.ucs.ccs.pojo.CcsDataDictType;
import com.dzmsoft.ucs.ccs.pojo.CcsDataDictTypeExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CcsDataDictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int countByExample(CcsDataDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByExample(CcsDataDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insert(CcsDataDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insertSelective(CcsDataDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    List<CcsDataDictType> selectByExample(CcsDataDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    CcsDataDictType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") CcsDataDictType record, @Param("example") CcsDataDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExample(@Param("record") CcsDataDictType record, @Param("example") CcsDataDictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKeySelective(CcsDataDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKey(CcsDataDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dict_type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    PageList<CcsDataDictType> selectByExample(CcsDataDictTypeExample example, PageBounds pageBounds);
}