package com.dzmsoft.ucs.ccs.dao;

import com.dzmsoft.ucs.ccs.pojo.CcsDataDictionaryTree;
import com.dzmsoft.ucs.ccs.pojo.CcsDataDictionaryTreeExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CcsDataDictionaryTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int countByExample(CcsDataDictionaryTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByExample(CcsDataDictionaryTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insert(CcsDataDictionaryTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insertSelective(CcsDataDictionaryTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    List<CcsDataDictionaryTree> selectByExample(CcsDataDictionaryTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    CcsDataDictionaryTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") CcsDataDictionaryTree record, @Param("example") CcsDataDictionaryTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExample(@Param("record") CcsDataDictionaryTree record, @Param("example") CcsDataDictionaryTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKeySelective(CcsDataDictionaryTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKey(CcsDataDictionaryTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_data_dictionary_tree
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    PageList<CcsDataDictionaryTree> selectByExample(CcsDataDictionaryTreeExample example, PageBounds pageBounds);
}