package com.dzmsoft.ucs.ccs.dao;

import com.dzmsoft.ucs.ccs.pojo.CcsTemplate;
import com.dzmsoft.ucs.ccs.pojo.CcsTemplateExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CcsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int countByExample(CcsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByExample(CcsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insert(CcsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int insertSelective(CcsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    List<CcsTemplate> selectByExample(CcsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    CcsTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") CcsTemplate record, @Param("example") CcsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByExample(@Param("record") CcsTemplate record, @Param("example") CcsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKeySelective(CcsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    int updateByPrimaryKey(CcsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccs_template
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    PageList<CcsTemplate> selectByExample(CcsTemplateExample example, PageBounds pageBounds);
}