package com.dzmsoft.ucs.base.pojo;

public class UcsDomain {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private Integer sort;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.app_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String appId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_domain.app_key
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String appKey;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.id
     * @return  the value of ucs_domain.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.id
     * @param id  the value for ucs_domain.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.name
     * @return  the value of ucs_domain.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.name
     * @param name  the value for ucs_domain.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.status
     * @return  the value of ucs_domain.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.status
     * @param status  the value for ucs_domain.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.sort
     * @return  the value of ucs_domain.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.sort
     * @param sort  the value for ucs_domain.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.description
     * @return  the value of ucs_domain.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.description
     * @param description  the value for ucs_domain.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.app_id
     * @return  the value of ucs_domain.app_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.app_id
     * @param appId  the value for ucs_domain.app_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_domain.app_key
     * @return  the value of ucs_domain.app_key
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_domain.app_key
     * @param appKey  the value for ucs_domain.app_key
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }
}