package com.dzmsoft.ucs.base.pojo;

public class UcsPermission {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.pid
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String pid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.type
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.url
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private Integer sort;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String domain;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.id
     * @return  the value of ucs_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.id
     * @param id  the value for ucs_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.pid
     * @return  the value of ucs_permission.pid
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.pid
     * @param pid  the value for ucs_permission.pid
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.type
     * @return  the value of ucs_permission.type
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.type
     * @param type  the value for ucs_permission.type
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.name
     * @return  the value of ucs_permission.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.name
     * @param name  the value for ucs_permission.name
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.url
     * @return  the value of ucs_permission.url
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.url
     * @param url  the value for ucs_permission.url
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.sort
     * @return  the value of ucs_permission.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.sort
     * @param sort  the value for ucs_permission.sort
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.description
     * @return  the value of ucs_permission.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.description
     * @param description  the value for ucs_permission.description
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.status
     * @return  the value of ucs_permission.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.status
     * @param status  the value for ucs_permission.status
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_permission.domain
     * @return  the value of ucs_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_permission.domain
     * @param domain  the value for ucs_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }
}