package com.dzmsoft.ucs.base.pojo;

public class UcsRolePermission {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_role_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_role_permission.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_role_permission.permission_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String permissionId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_role_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String domain;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_role_permission.id
     * @return  the value of ucs_role_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_role_permission.id
     * @param id  the value for ucs_role_permission.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_role_permission.role_id
     * @return  the value of ucs_role_permission.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_role_permission.role_id
     * @param roleId  the value for ucs_role_permission.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_role_permission.permission_id
     * @return  the value of ucs_role_permission.permission_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_role_permission.permission_id
     * @param permissionId  the value for ucs_role_permission.permission_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_role_permission.domain
     * @return  the value of ucs_role_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_role_permission.domain
     * @param domain  the value for ucs_role_permission.domain
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }
}