package com.dzmsoft.ucs.base.pojo;

public class UcsUserRole {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user_role.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user_role.user_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user_role.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user_role.id
     * @return  the value of ucs_user_role.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user_role.id
     * @param id  the value for ucs_user_role.id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user_role.user_id
     * @return  the value of ucs_user_role.user_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user_role.user_id
     * @param userId  the value for ucs_user_role.user_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user_role.role_id
     * @return  the value of ucs_user_role.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user_role.role_id
     * @param roleId  the value for ucs_user_role.role_id
     * @mbggenerated  Sat Oct 29 08:23:43 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}