package com.dzmsoft.ucs.base.pojo;

import java.util.Date;

public class UcsUser {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.id
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.username
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.password
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.salt
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String salt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.name
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.phone
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.email
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.status
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.create_time
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.domain
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String domain;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ucs_user.user_type
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    private String userType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.id
     * @return  the value of ucs_user.id
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.id
     * @param id  the value for ucs_user.id
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.username
     * @return  the value of ucs_user.username
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.username
     * @param username  the value for ucs_user.username
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.password
     * @return  the value of ucs_user.password
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.password
     * @param password  the value for ucs_user.password
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.salt
     * @return  the value of ucs_user.salt
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.salt
     * @param salt  the value for ucs_user.salt
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.name
     * @return  the value of ucs_user.name
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.name
     * @param name  the value for ucs_user.name
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.phone
     * @return  the value of ucs_user.phone
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.phone
     * @param phone  the value for ucs_user.phone
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.email
     * @return  the value of ucs_user.email
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.email
     * @param email  the value for ucs_user.email
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.status
     * @return  the value of ucs_user.status
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.status
     * @param status  the value for ucs_user.status
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.create_time
     * @return  the value of ucs_user.create_time
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.create_time
     * @param createTime  the value for ucs_user.create_time
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.domain
     * @return  the value of ucs_user.domain
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.domain
     * @param domain  the value for ucs_user.domain
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ucs_user.user_type
     * @return  the value of ucs_user.user_type
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ucs_user.user_type
     * @param userType  the value for ucs_user.user_type
     * @mbggenerated  Sat Oct 29 10:57:07 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }
}