package com.dzmsoft.ucs.ccs.pojo;

public class CcsDataDictType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dict_type.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dict_type.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dict_type.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dict_type.id
     *
     * @return the value of ccs_data_dict_type.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dict_type.id
     *
     * @param id the value for ccs_data_dict_type.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dict_type.name
     *
     * @return the value of ccs_data_dict_type.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dict_type.name
     *
     * @param name the value for ccs_data_dict_type.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dict_type.type
     *
     * @return the value of ccs_data_dict_type.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dict_type.type
     *
     * @param type the value for ccs_data_dict_type.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}