package com.dzmsoft.ucs.ccs.pojo;

import java.util.Date;

public class CcsDataDictionaryTree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.pid
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.level
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.state
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary_tree.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.id
     *
     * @return the value of ccs_data_dictionary_tree.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.id
     *
     * @param id the value for ccs_data_dictionary_tree.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.pid
     *
     * @return the value of ccs_data_dictionary_tree.pid
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.pid
     *
     * @param pid the value for ccs_data_dictionary_tree.pid
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.name
     *
     * @return the value of ccs_data_dictionary_tree.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.name
     *
     * @param name the value for ccs_data_dictionary_tree.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.status
     *
     * @return the value of ccs_data_dictionary_tree.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.status
     *
     * @param status the value for ccs_data_dictionary_tree.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.type
     *
     * @return the value of ccs_data_dictionary_tree.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.type
     *
     * @param type the value for ccs_data_dictionary_tree.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.description
     *
     * @return the value of ccs_data_dictionary_tree.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.description
     *
     * @param description the value for ccs_data_dictionary_tree.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.level
     *
     * @return the value of ccs_data_dictionary_tree.level
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.level
     *
     * @param level the value for ccs_data_dictionary_tree.level
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.state
     *
     * @return the value of ccs_data_dictionary_tree.state
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.state
     *
     * @param state the value for ccs_data_dictionary_tree.state
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.creator
     *
     * @return the value of ccs_data_dictionary_tree.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.creator
     *
     * @param creator the value for ccs_data_dictionary_tree.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.create_time
     *
     * @return the value of ccs_data_dictionary_tree.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.create_time
     *
     * @param createTime the value for ccs_data_dictionary_tree.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.updator
     *
     * @return the value of ccs_data_dictionary_tree.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.updator
     *
     * @param updator the value for ccs_data_dictionary_tree.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary_tree.update_time
     *
     * @return the value of ccs_data_dictionary_tree.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary_tree.update_time
     *
     * @param updateTime the value for ccs_data_dictionary_tree.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}