package com.dzmsoft.ucs.ccs.pojo;

import java.util.Date;

public class CcsDataDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.display_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String displayField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.value_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String valueField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_data_dictionary.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.id
     *
     * @return the value of ccs_data_dictionary.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.id
     *
     * @param id the value for ccs_data_dictionary.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.display_field
     *
     * @return the value of ccs_data_dictionary.display_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getDisplayField() {
        return displayField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.display_field
     *
     * @param displayField the value for ccs_data_dictionary.display_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setDisplayField(String displayField) {
        this.displayField = displayField == null ? null : displayField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.value_field
     *
     * @return the value of ccs_data_dictionary.value_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getValueField() {
        return valueField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.value_field
     *
     * @param valueField the value for ccs_data_dictionary.value_field
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setValueField(String valueField) {
        this.valueField = valueField == null ? null : valueField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.type
     *
     * @return the value of ccs_data_dictionary.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.type
     *
     * @param type the value for ccs_data_dictionary.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.status
     *
     * @return the value of ccs_data_dictionary.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.status
     *
     * @param status the value for ccs_data_dictionary.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.description
     *
     * @return the value of ccs_data_dictionary.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.description
     *
     * @param description the value for ccs_data_dictionary.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.creator
     *
     * @return the value of ccs_data_dictionary.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.creator
     *
     * @param creator the value for ccs_data_dictionary.creator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.create_time
     *
     * @return the value of ccs_data_dictionary.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.create_time
     *
     * @param createTime the value for ccs_data_dictionary.create_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.updator
     *
     * @return the value of ccs_data_dictionary.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.updator
     *
     * @param updator the value for ccs_data_dictionary.updator
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_data_dictionary.update_time
     *
     * @return the value of ccs_data_dictionary.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_data_dictionary.update_time
     *
     * @param updateTime the value for ccs_data_dictionary.update_time
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}