package com.dzmsoft.ucs.ccs.pojo;

public class CcsTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.content
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccs_template.vm_name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    private String vmName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.id
     *
     * @return the value of ccs_template.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.id
     *
     * @param id the value for ccs_template.id
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.name
     *
     * @return the value of ccs_template.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.name
     *
     * @param name the value for ccs_template.name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.type
     *
     * @return the value of ccs_template.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.type
     *
     * @param type the value for ccs_template.type
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.content
     *
     * @return the value of ccs_template.content
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.content
     *
     * @param content the value for ccs_template.content
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.status
     *
     * @return the value of ccs_template.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.status
     *
     * @param status the value for ccs_template.status
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.description
     *
     * @return the value of ccs_template.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.description
     *
     * @param description the value for ccs_template.description
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccs_template.vm_name
     *
     * @return the value of ccs_template.vm_name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public String getVmName() {
        return vmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccs_template.vm_name
     *
     * @param vmName the value for ccs_template.vm_name
     *
     * @mbggenerated Sat Nov 19 08:49:31 CST 2016
     */
    public void setVmName(String vmName) {
        this.vmName = vmName == null ? null : vmName.trim();
    }
}